version: '3.0'

services:
  jeeves-master:
    restart: always
    image: adamlavie/jeeves-master:0.1
    networks:
      - jeeves-network
    expose:
      - "8080"
      - "7778"
    build:
      context: .
    depends_on:
      - "postgres-db"
      - "rabbitmq-broker"
    environment:
      POSTGRES_HOST_PORT_ENV: "5432"
      POSTGRES_USERNAME_ENV: "postgres"
      POSTGRES_PASSWORD_ENV: "postgres"

      RABBITMQ_HOST_PORT_ENV: "5672"
      RABBITMQ_USERNAME_ENV: "guest"
      RABBITMQ_PASSWORD_ENV: "guest"

      POSTGRES_HOST_IP_ENV: postgres-db
      RABBITMQ_HOST_IP_ENV: rabbitmq-broker

  jeeves-minion:
    restart: always
    image: adamlavie/jeeves-minion:0.1
    build:
      context: ./../jeeves-minion
    networks:
      - jeeves-network
    depends_on:
      - "jeeves-master"
    environment:
      POSTGRES_HOST_PORT_ENV: "5432"
      POSTGRES_USERNAME_ENV: "postgres"
      POSTGRES_PASSWORD_ENV: "postgres"

      RABBITMQ_HOST_PORT_ENV: "5672"
      RABBITMQ_USERNAME_ENV: "guest"
      RABBITMQ_PASSWORD_ENV: "guest"

      POSTGRES_HOST_IP_ENV: postgres-db
      RABBITMQ_HOST_IP_ENV: rabbitmq-broker

  postgres-db:
    restart: always
    image: postgres:latest
    networks:
      - jeeves-network
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  rabbitmq-broker:
    restart: always
    image: rabbitmq:latest
    networks:
      - jeeves-network
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

networks:
  jeeves-network:
