version: '3.0'

services:
  jeeves-master:
    restart: always
    image: adamlavie/jeeves-master:master
    networks:
      - jeeves-network
    expose:
      - "8080"
      - "7778"
    build:
      context: .
    depends_on:
      - "postgres-db"
      - "rabbitmq-broker"
    environment:
      POSTGRES_HOST_PORT_ENV: "5432"
      POSTGRES_USERNAME_ENV: "postgres"
      POSTGRES_PASSWORD_ENV: "postgres"

      RABBITMQ_HOST_PORT_ENV: "5672"
      RABBITMQ_USERNAME_ENV: "guest"
      RABBITMQ_PASSWORD_ENV: "guest"

      POSTGRES_HOST_IP_ENV: postgres-db
      RABBITMQ_HOST_IP_ENV: rabbitmq-broker

  jeeves-minion:
    restart: always
    image: adamlavie/jeeves-minion:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    build:
      context: ./../jeeves-minion
    networks:
      - jeeves-network
    expose:
      - "7777"
    depends_on:
      - "jeeves-master"
    environment:
      POSTGRES_HOST_PORT_ENV: "5432"
      POSTGRES_USERNAME_ENV: "postgres"
      POSTGRES_PASSWORD_ENV: "postgres"

      RABBITMQ_HOST_PORT_ENV: "5672"
      RABBITMQ_USERNAME_ENV: "guest"
      RABBITMQ_PASSWORD_ENV: "guest"

      POSTGRES_HOST_IP_ENV: postgres-db
      RABBITMQ_HOST_IP_ENV: rabbitmq-broker

  postgres-db:
    restart: always
    image: postgres:latest
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    networks:
      - jeeves-network
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  rabbitmq-broker:
    restart: always
    image: rabbitmq:latest
#    volumes:
#      - /tmp/rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-broker
    networks:
      - jeeves-network
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

networks:
  jeeves-network:
